
# adjust to your needs

ARDUINO_DIR = /home/stefan/installer/arduino-1.8.10
# this was needed in my install
#ARDUINO_VERSION = 10810
ALTERNATE_CORE_PATH=/home/stefan/.arduino15/packages/SparkFun/hardware/avr/1.1.12
#use this to disable auto reset (needed sometimes to manually reset/flash the pro micro)
#RESET_CMD = true


ALTERNATE_CORE = SparkFun

BOARD_TAG = promicro
BOARD_SUB = 8MHzatmega32U4

ARDUINO_PORT = /dev/ttyACM0

#USER_LIB_PATH := $(realpath ./libraries)
ARDMK_DIR := $(realpath ./Arduino-Makefile)

include $(ARDMK_DIR)/Arduino.mk
